###
GET http://localhost:8080/movie/TEMP


###
GET http://localhost:8080/movies

###
GET http://localhost:8080/auth/ticket
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLsoJXrr7zsmrAiLCJhdXRoIjoiUk9MRV9VU0VSIn0.nuNd3FDt152ovuTIXvAabUm6Rd_fIDSC-4OVx01Ab-I


### 54.180.160.9

###
GET http://54.180.134.85:8080/movies