### ticketing
GET http://3.36.70.96:8080/auth/ticket

### select
POST http://3.36.70.96:8080/auth/ticket/select
accept: */*
Content-Type: application/json

{
 "title":"공조2-인터내셔날",
 "town": "춘천",
  "date": "20220915"
}


### seat
POST http://3.36.70.96:8080/auth/ticket/seat
accept: */*
Content-Type: application/json

{
 "title":"공조2-인터내셔날",
 "town": "춘천",
  "date": "20220915",
  "time" : "12:00"
}



### buyTicket
POST http://3.36.70.96:8080/auth/ticket/seat/buy
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaWHN3ZzdMYTZkVksxTGpVX0JiSGx5RHlVYnVZUHVQdlNBWVFNZTlxN2YwIiwibmFtZSI6IuygleuvvOyasCIsImF1dGgiOiJST0xFX1VTRVIifQ.0qGwrvLxYuxqzVOERs6BVMShQVZrVMKp2TdS2KeoOTI
Content-Type: application/json

{
  "title":"공조2-인터내셔날",
  "town": "춘천",
  "date": "20220915",
  "time" : "12:00",
  "seat" : "I12,I13",
  "memberCount" : 2
}

### buyTicket2
POST http://localhost:8080/auth/ticket/seat/buy
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaWHN3ZzdMYTZkVksxTGpVX0JiSGx5RHlVYnVZUHVQdlNBWVFNZTlxN2YwIiwibmFtZSI6IuygleuvvOyasCIsImF1dGgiOiJST0xFX1VTRVIifQ.0qGwrvLxYuxqzVOERs6BVMShQVZrVMKp2TdS2KeoOTI
Content-Type: application/json

{
  "title":"공조2-인터내셔날",
  "town": "춘천",
  "date": "20220915",
  "time" : "12:00",
  "seat" : "A12,A15",
  "memberCount" : 2
}

###
GET http://localhost:8080/user/movielog
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaWHN3ZzdMYTZkVksxTGpVX0JiSGx5RHlVYnVZUHVQdlNBWVFNZTlxN2YwIiwibmFtZSI6IuygleuvvOyasCIsImF1dGgiOiJST0xFX1VTRVIifQ.0qGwrvLxYuxqzVOERs6BVMShQVZrVMKp2TdS2KeoOTI

###
POST http://3.36.70.96:8080/movie/like/20
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJab01GYXNjcENPNEgwdUQ4QmhfVGNyai1IQ2x6RGdUOTUwQnBWMWluWDJnIiwibmFtZSI6IuygleuvvOyasCIsImF1dGgiOiJST0xFX1VTRVIifQ.EGwb8rOT6HuNG6Jy-jzoKeCURQlCNNKrM1yaVVPnaCg


Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaWHN3ZzdMYTZkVksxTGpVX0JiSGx5RHlVYnVZUHVQdlNBWVFNZTlxN2YwIiwibmFtZSI6IuygleuvvOyasCIsImF1dGgiOiJST0xFX1VTRVIifQ.0qGwrvLxYuxqzVOERs6BVMShQVZrVMKp2TdS2KeoOTI